import {
    Code2,
    Layers,
    Database,
    Cloud,
    Brain,
    Wrench,
} from 'lucide-react';

export const techCategories = [
    {
        title: 'Languages',
        icon: Code2,
        variant: 'primary',
        skills: [
            'C',
            'C++',
            'C#',
            'Python',
            'JavaScript',
            'TypeScript',
            'Java',
            'SQL',
            'HTML5',
            'CSS3',
            'PHP',
        ],
    },
    {
        title: 'Frameworks & Tools',
        icon: Layers,
        variant: 'secondary',
        skills: [
            '.NET Core',
            'ASP.NET Core',
            'Next.js',
            'React',
            'Angular',
            'Node.js',
            'Express.js',
            'Laravel',
            'Django',
            'FastAPI',
            'Tailwind CSS',
            'Bootstrap',
            'Vite',
            'EF Core',
            'NHibernate',
        ],
    },
    {
        title: 'Databases',
        icon: Database,
        variant: 'primary',
        skills: [
            'MSSQL',
            'PostgreSQL',
            'MongoDB',
            'MySQL',
            'Firebase',
            'Firestore',
            'Realtime DB',
        ],
    },
    {
        title: 'Cloud & DevOps',
        icon: Cloud,
        variant: 'secondary',
        skills: [
            'Microsoft Azure',
            'Vercel',
            'Plesk',
            'CI/CD Pipelines',
            'Git',
            'GitHub',
        ],
    },
    {
        title: 'AI & Integrations',
        icon: Brain,
        variant: 'primary',
        skills: [
            'RAG',
            'Claude API',
            'OpenAI',
            'Gamma API',
            'LLM Integration',
            'Multi-Agent Systems',
            'TensorFlow',
            'Scikit-learn',
        ],
    },
    {
        title: 'Architecture & Practices',
        icon: Wrench,
        variant: 'secondary',
        list: [
            'Clean Architecture',
            'SOLID Principles',
            'JWT Authentication',
            'RBAC',
            'REST APIs',
            'React Hooks',
            'Repository Pattern',
            'Arabic RTL Support',
        ],
    },
];
